---
name: Collect and print async labels

'on':
  pull_request:
    types:
      - opened
      - reopened

jobs:
  print-labels:
    runs-on: ubuntu-latest
    name: Print labels
    steps:
      - name: Collect labels
        env:
          GH_TOKEN: ${{ github.token }}
          nr: ${{ github.event.issue.number }}
          ispr: ${{ github.event.issue.pull_request }}

        id: collect_labels
        run: |
          gh auth login
          labels="$(gh label list --jq '.[].name | select(startswith("async-"))')"
          body_text="The following labels are available: ${labels}"
          method="pr"
          [ "${ispr}" == "null" ] && method="issue"
          gh "${method}" comment "${nr}" --body "${body_text}"
